
/****** Object:  Database [DBWinFormm]    Script Date: 5/15/2020 3:21:22 PM ******/
CREATE DATABASE [DBWinFormm]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DBWinFormm', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\DBWinFormm.mdf' , SIZE = 3136KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DBWinFormm_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\DBWinFormm_log.ldf' , SIZE = 784KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [DBWinFormm] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DBWinFormm].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DBWinFormm] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DBWinFormm] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DBWinFormm] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DBWinFormm] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DBWinFormm] SET ARITHABORT OFF 
GO
ALTER DATABASE [DBWinFormm] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [DBWinFormm] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DBWinFormm] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DBWinFormm] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DBWinFormm] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DBWinFormm] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DBWinFormm] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DBWinFormm] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DBWinFormm] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DBWinFormm] SET  ENABLE_BROKER 
GO
ALTER DATABASE [DBWinFormm] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DBWinFormm] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DBWinFormm] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DBWinFormm] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DBWinFormm] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DBWinFormm] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DBWinFormm] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DBWinFormm] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DBWinFormm] SET  MULTI_USER 
GO
ALTER DATABASE [DBWinFormm] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DBWinFormm] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DBWinFormm] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DBWinFormm] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
USE [DBWinFormm]
GO
/****** Object:  Table [dbo].[Angajat]    Script Date: 5/15/2020 3:21:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Angajat](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[An] [int] NOT NULL,
	[Categorie] [int] NULL,
	[Adresa] [varchar](100) NULL,
	[Vanzari] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Categorie]    Script Date: 5/15/2020 3:21:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Categorie](
	[IdCategorie] [int] IDENTITY(1,1) NOT NULL,
	[NumeCategorie] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[IdCategorie] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[login]    Script Date: 5/15/2020 3:21:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[login](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[UserName] [varchar](50) NULL,
	[Password] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Angajat]  WITH CHECK ADD FOREIGN KEY([Categorie])
REFERENCES [dbo].[Categorie] ([IdCategorie])
GO
USE [master]
GO
ALTER DATABASE [DBWinFormm] SET  READ_WRITE 
GO
